export const WORLD_SPEED = 1000;
export const QUANTITY_OF_FOO_REQUIRED_TO_CRAFT_FOOBAR = 1;
export const QUANTITY_OF_BAR_REQUIRED_TO_CRAFT_FOOBAR = 1;
export const QUANTITY_OF_FOO_REQUIRED_TO_BUY_ROBOT = 6;
export const FOOBAR_SELLING_PRICE = 1;
